# 
# Copyright (c) 2018 Intel Labs.
#
# authors: Bernd Gassmann (bernd.gassmann@intel.com)
#
# This represents an info message of the ego vehicle

Header header

# the restrictions
EgoVehicleControlMaxima restrictions

# the target values
EgoVehicleControlTarget target

# the currently measured values
EgoVehicleControlCurrent current

# the current control state
EgoVehicleControlState state

# the current control output to CARLA
CarlaVehicleControl output
