#
# Copyright (c) 2019 Intel Corporation
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#

os: linux
services: docker

cache:
  - apt

addons:
  apt:
    packages:
    - python-pip

jobs:
  include:
    - name: "Docker Melodic"
      env:
        - ROS_DISTRO=melodic
        - PYTHON_SUFFIX="2.7"
    - name: "Docker Noetic"
      env:
        - ROS_DISTRO=noetic
        - PYTHON_SUFFIX="3.7"

script: cd docker && ./build.sh --build-arg ROS_VERSION=$ROS_DISTRO --build-arg PYTHON_VERSION=$PYTHON_SUFFIX

after_failure:
  - tail --lines=2000 build.log

notifications:
  email: false
