#
# Copyright (c) 2019 Intel Corporation
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.
#

os: linux

stages:
  - check
  - test
  - docker

cache:
  - apt

addons:
  apt:
    packages:
    - python-pip

jobs:
  include:
    - name: "Check code formatting"
      stage: check
      before_install: skip
      install: pip install --user -r requirements.txt
      script:
        - make check_format
    - name: "Xenial Kinetic"
      stage: test
      dist: xenial
      env:
        - ROS_DISTRO=kinetic
        - PYTHON_SUFFIX=""
    - name: "Bionic Melodic"
      dist: bionic
      env:
        - ROS_DISTRO=melodic
        - PYTHON_SUFFIX=""
    - name: "Focal Noetic"
      dist: focal
      env:
        - ROS_DISTRO=noetic
        - PYTHON_SUFFIX=3
      addons:
        apt:
          packages:
          - python3-pip
    - name: "Docker Melodic"
      stage: docker
      services: docker
      before_install: skip
      install: skip
      script: cd docker && ./build.sh --build-arg ROS_VERSION=melodic
    - name: "Docker Noetic"
      services: docker
      before_install: skip
      install: skip
      script: cd docker && ./build.sh --build-arg ROS_VERSION=noetic --build-arg PYTHON_VERSION=3.7

before_install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - sudo apt update
  - sudo apt install -y ros-$ROS_DISTRO-desktop-full python$PYTHON_SUFFIX-osrf-pycommon python$PYTHON_SUFFIX-catkin-tools python$PYTHON_SUFFIX-catkin-pkg python$PYTHON_SUFFIX-catkin-pkg-modules python$PYTHON_SUFFIX-rosdep python$PYTHON_SUFFIX-wstool

install:
  - pip$PYTHON_SUFFIX install --user -r requirements.txt
  - mkdir ros-bridge/
  - shopt -s dotglob
  - shopt -s extglob
  - mv !(ros-bridge) ros-bridge/
  - mkdir -p catkin_ws/src
  - cd catkin_ws/src
  - ln -s ../../ros-bridge
  - cd ..
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - sudo rosdep init
  - rosdep update
  - rosdep install --from-paths src --ignore-src -r

script:
  - catkin build
  - export SCENARIO_RUNNER_PATH=""  # the env var needs to be set for testing
  - if [ ! $ROS_DISTRO -eq kinetic ]; then catkin test; fi;
  - catkin config --install
  - source devel/setup.bash
  - cd src/ros-bridge
  - if [ ! $ROS_DISTRO -eq noetic ]; then make pylint; fi;

after_failure:
  - tail --lines=2000 build.log

notifications:
  email: false
