#!/usr/bin/env python

import sys

from rqt_carla_control.rqt_carla_control import CarlaControl
from rqt_gui.main import Main

plugin = 'rqt_carla_control'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))
